- name: Fetch and Setup MetalANGLE
        run: |
          # 1. Create the libs folder since it doesn't exist in the repo
          mkdir -p Mindustry/ios/libs
          
          # 2. Download MetalANGLE
          curl -L -s -o metalangle.zip "https://github.com/libgdx/MetalANGLEKit/releases/download/v1.2.1/metalanglekit.zip"
          unzip -q -o metalangle.zip -d temp_metalangle
          
          # 3. Find MetalANGLEKit.framework wherever it extracted and copy it to ios/libs/
          find temp_metalangle -name "MetalANGLEKit.framework" -exec cp -R {} Mindustry/ios/libs/ \;
          
          # 4. Clean up temporary files
          rm -rf temp_metalangle metalangle.zip
